---
- name: Ensure local user exists
  become: True
  user:
    name: "{{ restic_local_user }}"
    system: yes
    home: "/var/{{ restic_local_user }}"
    createhome: yes

- name: Install restic
  become: True
  apt:
    name: restic

- name: Configure restic systemd units
  become: True
  template:
    src: "restic.{{ item }}.j2"
    dest: "/etc/systemd/system/restic.{{ restic_name }}.{{ item }}"
  with_items:
    - service
    - timer
  notify: restart restic timer

- name: Check if restic backup initialized
  become: True
  become_user: "{{ restic_local_user }}"
  shell: restic stats
  environment:
    RESTIC_REPOSITORY: "{{ restic_repository }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
  register: restic_stat
  changed_when: False
  failed_when: False

- name: Initialize restic backup
  become: True
  become_user: "{{ restic_local_user }}"
  shell: restic init
  environment:
    RESTIC_REPOSITORY: "{{ restic_repository }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
  when: restic_stat.rc != 0
